### ISSUE TITLE
Unable to open app window after it minimizes to tray

### ISSUE THREAD

**Issue by gregwhorley** [jhegg/github-desktop-notifier#8]
If I click Close on the app's window, it will minimize to the system tray or whatever it is called in Linux. If I open the system tray, I can see the icon for GN but a single or double click will not open the app.

Also, if I minimize the window, I have to right click on the Github Desktop Notifier 'box' on the task bar and click 'Unminimize' to open the app again. Simply clicking on the box does nothing for me.

I am running on CentOS 7 using Gnome 3.8.4 by the way.

**Comment by jhegg** [comment]
After some research, I found this Java defect: [MouseListener installed on java.awt.TrayIcon does not receive events on Gnome 3 ](https://bugs.openjdk.java.net/browse/JDK-8040667). It's set to a low priority, probably because it's in super old AWT code, and AFAIK future plans are to re-implement the system tray functionality in JavaFX.

So, I can try giving the workaround a shot. Although there are then other bugs, such as the tray icon image only showing in the upper-left quarter of the icon instead of filling it, and also the annoying and ever-present "JavaEmbeddedFrame" taskbar entry that can't be opened or closed.

Perhaps I should just detect if Gnome is being used, and then disable the tray icon entirely.

**Comment by jhegg** [comment]
It seems to work fine under XFCE and KDE. It has similar problems in Cinnamon as it does with Gnome, though.

How frustrating.

Perhaps a better approach than detecting certain desktop environments would be to offer an option in the preferences. Something like `Use System Tray icon (y/n)`. If it's not enabled, then it can't minimize to tray.

**Comment by jhegg** [comment]
@gwhorley Ok, I've added a setting so you can disable the system tray icon, and then it will get rid of the not-so-hidden hidden window, and the minimize and close behavior should be just like a regular app. Let me know what you think.
